version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: eu-north-1
    ECR_BACKEND_REPO: 452202271953.dkr.ecr.eu-north-1.amazonaws.com/auto-blog-backend
    ECR_FRONTEND_REPO: 452202271953.dkr.ecr.eu-north-1.amazonaws.com/auto-blog-frontend

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION \
        | docker login --username AWS --password-stdin $(echo $ECR_BACKEND_REPO | cut -d'/' -f1)

      - echo "Resolving image tag..."
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "Using tag: $IMAGE_TAG"

  build:
    commands:
      - echo "Building backend image..."
      - docker build -t $ECR_BACKEND_REPO:$IMAGE_TAG ./server
      - docker tag $ECR_BACKEND_REPO:$IMAGE_TAG $ECR_BACKEND_REPO:latest

      - echo "Building frontend image..."
      - docker build -t $ECR_FRONTEND_REPO:$IMAGE_TAG ./client
      - docker tag $ECR_FRONTEND_REPO:$IMAGE_TAG $ECR_FRONTEND_REPO:latest

  post_build:
    commands:
      - echo "Pushing backend image to ECR..."
      - docker push $ECR_BACKEND_REPO:$IMAGE_TAG
      - docker push $ECR_BACKEND_REPO:latest

      - echo "Pushing frontend image to ECR..."
      - docker push $ECR_FRONTEND_REPO:$IMAGE_TAG
      - docker push $ECR_FRONTEND_REPO:latest

artifacts:
  files:
    - "**/*"
